title: Don't Waste My Time.
author:
  name: Don't Waste My Time â™”
markdown: kramdown
permalink: /:categories/:title/
url: "https://pleasedontwastemytime26-arch.github.io"
baseurl: "/book-blog"
words_per_minute: 200
